services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      PYTHON_VERSION: 3.12.5
